Server:
  Port: 5005
  RunMode: debug
  logger:
    filePath: ../logs/logs.log
    Encoding: json
    level: debug
  cors:
    allowOrigins: "*"
  postgres:
    host: localhost
    port: 3000
    database: my_db
    sslMode: false
  redis:
    host: localhost
    port: 6379
    password: password
    db: 0
    minIdleConnections: 100
    poolSIze: 5000
    poolTimeout: 240


